// 由运行时 app.openapi() v1.2.0 核对。用于自动检查 72 个操作均有明确前端处理策略。
export const API_OPERATION_CONTRACT = [
  { method: 'GET', path: '/', wrapper: null, status: 'backend_only', note: '后端部署根健康检查，不经 Vite /api 代理', deprecated: false },
  { method: 'GET', path: '/api/v1/', wrapper: 'getApiHealth', status: 'connected', note: '管理端健康状态', deprecated: false },
  { method: 'POST', path: '/api/v1/admin/lta/bus-arrival/refresh', wrapper: 'refreshAdminLtaBusArrival', status: 'connected', note: '管理端', deprecated: false },
  { method: 'POST', path: '/api/v1/admin/lta/traffic-speed-bands/refresh', wrapper: 'refreshAdminLtaTrafficSpeedBands', status: 'connected', note: '管理端', deprecated: false },
  { method: 'POST', path: '/api/v1/ai/travel', wrapper: 'askAiTravel', status: 'connected', note: '首页与 AI 页', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-lines', wrapper: 'getLegacyBusLines', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-lines/{line_id}', wrapper: 'getLegacyBusLineDetail', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-lines/{line_id}/geometry', wrapper: 'getLegacyBusLineGeometry', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-lines/{line_id}/map', wrapper: 'getLegacyBusLineMap', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-lines/{line_id}/stations', wrapper: 'getLegacyBusLineStations', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-stations', wrapper: 'getLegacyBusStations', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-stations/nearby', wrapper: 'getLegacyNearbyBusStations', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-stations/{station_id}', wrapper: 'getLegacyBusStationDetail', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/bus-vehicles/realtime', wrapper: 'getLegacyRealtimeBusVehicles', status: 'compatibility', note: '旧路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/eta', wrapper: 'getEta', status: 'connected', note: '线路详情、首页、车辆详情', deprecated: false },
  { method: 'GET', path: '/api/v1/history/eta/line/{line_id}', wrapper: 'getEtaPredictionsByLine', status: 'connected', note: '线路详情历史', deprecated: false },
  { method: 'GET', path: '/api/v1/history/eta/{vehicle_id}/{target_station_id}', wrapper: 'getEtaPredictionForVehicle', status: 'encapsulated', note: '已封装，按需调用', deprecated: false },
  { method: 'GET', path: '/api/v1/history/load/line/{line_id}', wrapper: 'getLoadPredictionsByLine', status: 'connected', note: '线路详情/客流页', deprecated: false },
  { method: 'GET', path: '/api/v1/history/load/{line_id}', wrapper: 'getLoadPrediction', status: 'connected', note: '客流页兜底', deprecated: false },
  { method: 'GET', path: '/api/v1/history/passenger-flow', wrapper: 'getPassengerFlowTrend', status: 'connected', note: '首页/客流页/管理端', deprecated: false },
  { method: 'GET', path: '/api/v1/history/passenger-flow/prediction', wrapper: 'getPassengerFlowPrediction', status: 'deferred', note: '第一阶段按文档暂不接页面', deprecated: false },
  { method: 'GET', path: '/api/v1/history/passenger-load', wrapper: 'getPassengerLoadHistory', status: 'encapsulated', note: '通用历史封装', deprecated: false },
  { method: 'GET', path: '/api/v1/history/predictions', wrapper: 'getPredictionHistory', status: 'encapsulated', note: '通用历史封装', deprecated: false },
  { method: 'GET', path: '/api/v1/lines', wrapper: 'getLines', status: 'connected', note: '线路页/地图/管理端', deprecated: false },
  { method: 'POST', path: '/api/v1/lines', wrapper: 'createLine', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'PATCH', path: '/api/v1/lines/stations/{line_station_id}', wrapper: 'updateLineStation', status: 'connected', note: '管理端站序', deprecated: false },
  { method: 'DELETE', path: '/api/v1/lines/stations/{line_station_id}', wrapper: 'removeStationFromLine', status: 'connected', note: '管理端站序', deprecated: false },
  { method: 'GET', path: '/api/v1/lines/{line_id}', wrapper: 'getLineDetail', status: 'connected', note: '线路详情', deprecated: false },
  { method: 'PATCH', path: '/api/v1/lines/{line_id}', wrapper: 'updateLine', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'DELETE', path: '/api/v1/lines/{line_id}', wrapper: 'deleteLine', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'GET', path: '/api/v1/lines/{line_id}/stations', wrapper: 'getLineStations', status: 'connected', note: '线路详情/管理端站序', deprecated: false },
  { method: 'POST', path: '/api/v1/lines/{line_id}/stations', wrapper: 'addStationToLine', status: 'connected', note: '管理端站序', deprecated: false },
  { method: 'GET', path: '/api/v1/location/nearby', wrapper: 'getLegacyNearbyLocation', status: 'compatibility', note: '旧单数路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/location/{station_id}', wrapper: 'getLegacyLocationDetail', status: 'compatibility', note: '旧单数路径兼容', deprecated: false },
  { method: 'GET', path: '/api/v1/locations/map/stations', wrapper: 'getLocationMapStations', status: 'encapsulated', note: '已封装，地图主用 /map/stations', deprecated: false },
  { method: 'GET', path: '/api/v1/locations/nearby', wrapper: 'getNearbyLocations', status: 'connected', note: '首页定位', deprecated: false },
  { method: 'GET', path: '/api/v1/locations/search', wrapper: 'searchLocations', status: 'connected', note: '首页搜索', deprecated: false },
  { method: 'GET', path: '/api/v1/locations/{location_id}', wrapper: 'getLocationDetail', status: 'encapsulated', note: '已封装，按需详情', deprecated: false },
  { method: 'GET', path: '/api/v1/map/lines', wrapper: 'getMapLines', status: 'connected', note: '首页地图', deprecated: false },
  { method: 'GET', path: '/api/v1/map/road-segments', wrapper: 'getRoadSegments', status: 'connected', note: '首页地图线路几何兜底', deprecated: false },
  { method: 'GET', path: '/api/v1/map/stations', wrapper: 'getMapStations', status: 'connected', note: '首页地图', deprecated: false },
  { method: 'POST', path: '/api/v1/passenger-load-prediction', wrapper: 'predictPassengerLoad', status: 'connected', note: '首页/线路/车辆', deprecated: false },
  { method: 'POST', path: '/api/v1/recommend-routes', wrapper: 'recommendRoutes', status: 'connected', note: '首页', deprecated: false },
  { method: 'POST', path: '/api/v1/simulation/lta-bus-arrival/refresh', wrapper: 'refreshLtaBusArrival', status: 'deprecated', note: '仅保留旧调用兼容', deprecated: true },
  { method: 'POST', path: '/api/v1/simulation/prediction-results', wrapper: 'updatePredictionResult', status: 'encapsulated', note: '内部仿真写接口', deprecated: false },
  { method: 'PATCH', path: '/api/v1/simulation/vehicle-status/{vehicle_id}', wrapper: 'updateVehicleStatus', status: 'encapsulated', note: '内部仿真写接口', deprecated: false },
  { method: 'GET', path: '/api/v1/stations', wrapper: 'getStations', status: 'connected', note: '管理端', deprecated: false },
  { method: 'POST', path: '/api/v1/stations', wrapper: 'createStation', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'GET', path: '/api/v1/stations/coordinates/all', wrapper: 'getAllStationCoordinates', status: 'encapsulated', note: '地图辅助封装', deprecated: false },
  { method: 'GET', path: '/api/v1/stations/nearby', wrapper: null, status: 'unsupported', note: '运行时仅返回方法提示；正式调用 POST', deprecated: false },
  { method: 'POST', path: '/api/v1/stations/nearby', wrapper: 'searchNearbyStations', status: 'encapsulated', note: '已封装，首页使用 locations/nearby', deprecated: false },
  { method: 'GET', path: '/api/v1/stations/{station_id}', wrapper: 'getStationDetail', status: 'encapsulated', note: '已封装', deprecated: false },
  { method: 'PATCH', path: '/api/v1/stations/{station_id}', wrapper: 'updateStation', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'DELETE', path: '/api/v1/stations/{station_id}', wrapper: 'deleteStation', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'GET', path: '/api/v1/stations/{station_id}/lines', wrapper: 'getStationLines', status: 'connected', note: '管理端经过线路', deprecated: false },
  { method: 'POST', path: '/api/v1/travel-experience/evaluate', wrapper: 'evaluateTravelExperience', status: 'encapsulated', note: '推荐能力独立封装', deprecated: false },
  { method: 'POST', path: '/api/v1/users/login', wrapper: 'loginUser', status: 'connected', note: '登录页', deprecated: false },
  { method: 'GET', path: '/api/v1/users/me', wrapper: 'getCurrentUser', status: 'connected', note: '登录/个人中心', deprecated: false },
  { method: 'PATCH', path: '/api/v1/users/me', wrapper: 'updateCurrentUser', status: 'connected', note: '个人中心', deprecated: false },
  { method: 'GET', path: '/api/v1/users/me/favorites', wrapper: 'getUserFavorites', status: 'connected', note: '个人中心', deprecated: false },
  { method: 'POST', path: '/api/v1/users/me/favorites', wrapper: 'addUserFavorite', status: 'connected', note: '个人中心', deprecated: false },
  { method: 'DELETE', path: '/api/v1/users/me/favorites/{favorite_id}', wrapper: 'deleteUserFavorite', status: 'connected', note: '个人中心', deprecated: false },
  { method: 'GET', path: '/api/v1/users/me/query-history', wrapper: 'getUserQueryHistory', status: 'connected', note: '个人中心', deprecated: false },
  { method: 'POST', path: '/api/v1/users/register', wrapper: 'registerUser', status: 'connected', note: '注册页', deprecated: false },
  { method: 'GET', path: '/api/v1/vehicles', wrapper: 'getVehicles', status: 'connected', note: '车辆/管理端', deprecated: false },
  { method: 'POST', path: '/api/v1/vehicles', wrapper: 'createVehicle', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'GET', path: '/api/v1/vehicles/line/{line_id}', wrapper: 'getVehiclesByLine', status: 'connected', note: '线路详情兜底', deprecated: false },
  { method: 'GET', path: '/api/v1/vehicles/realtime', wrapper: 'getRealtimeVehicles', status: 'connected', note: '首页/线路/车辆', deprecated: false },
  { method: 'GET', path: '/api/v1/vehicles/{vehicle_id}', wrapper: 'getVehicleDetail', status: 'connected', note: '车辆详情', deprecated: false },
  { method: 'PATCH', path: '/api/v1/vehicles/{vehicle_id}', wrapper: 'updateVehicle', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'DELETE', path: '/api/v1/vehicles/{vehicle_id}', wrapper: 'deleteVehicle', status: 'connected', note: '管理端 CRUD', deprecated: false },
  { method: 'POST', path: '/api/v1/walking-time-estimation', wrapper: 'estimateWalkingTime', status: 'encapsulated', note: '推荐能力独立封装', deprecated: false },
]
